// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdkf4UeU13X6pAlSY9ds4BoVIsWurA6I4',
    appId: '1:315703827909:web:1e54db56155875fa0bffac',
    messagingSenderId: '315703827909',
    projectId: 'fir-demotest-49ead',
    authDomain: 'fir-demotest-49ead.firebaseapp.com',
    storageBucket: 'fir-demotest-49ead.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuFsj9tBeajzIct9XIFz6EP2-tycqyWEE',
    appId: '1:315703827909:android:db368a54bf21194a0bffac',
    messagingSenderId: '315703827909',
    projectId: 'fir-demotest-49ead',
    storageBucket: 'fir-demotest-49ead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXN7Mep_3PEgmU78PBQTnobmRnSJtoRcY',
    appId: '1:315703827909:ios:aa5226c7593313790bffac',
    messagingSenderId: '315703827909',
    projectId: 'fir-demotest-49ead',
    storageBucket: 'fir-demotest-49ead.appspot.com',
    iosClientId: '315703827909-rqvhut9t52c885b4q5o3fms0dd9jp33f.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXN7Mep_3PEgmU78PBQTnobmRnSJtoRcY',
    appId: '1:315703827909:ios:aa5226c7593313790bffac',
    messagingSenderId: '315703827909',
    projectId: 'fir-demotest-49ead',
    storageBucket: 'fir-demotest-49ead.appspot.com',
    iosClientId: '315703827909-rqvhut9t52c885b4q5o3fms0dd9jp33f.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedemo',
  );
}
